dist: bionic
sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose --all
  - sudo /home/travis/.cargo/bin/cargo test --verbose --all
