name: ripping
adopt-info: ripping
version: git
title: Ripping
summary: Ping toolbox
description: |
  Ripping is a ping toolbox.
license: Apache-2.0
contact: joe@josephb.org

grade: stable
confinement: strict
type: app
base: core24

apps:
  ripping:
    command: bin/ripping
    plugs:
      - network-observe

parts:
  ripping:
    source: .
    plugin: rust
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --abbrev=0)"
