name: ripping
adopt-info: ripping
version: git
summary: Ping toolbox
description: |
  Ripping is a ping toolbox.

grade: stable
confinement: strict
type: app
base: core24

apps:
  ripping:
    command: ripping
    plugs:
      - network-observe

parts:
  ripping:
    source: .
    plugin: rust
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --abbrev=0)"
