name: ripping
version: git
summary: Ping toolbox
description: |
  Ripping is a ping toolbox.

grade: stable
confinement: strict

apps:
  ripping:
    command: ripping
    plugs:
      - network-observe

parts:
  ripping:
    source: .
    plugin: rust
    build-attributes: [no-system-libraries]
