name: ripping
version: git
version-script: |
  git describe --tags --abbrev=0
summary: Ping toolbox
description: |
  Ripping is a ping toolbox.

grade: stable
confinement: strict
type: app
base: core22

apps:
  ripping:
    command: ripping
    plugs:
      - network-observe

parts:
  ripping:
    source: .
    plugin: rust
