name: Test

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          sudo bash -c "
            export PATH=\"/home/runner/.cargo/bin:${PATH}\"
            rustup default stable
            cargo test --verbose
          "
