name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install liboping-dev -y

      - name: Run tests
        run: |
          sudo /home/runner/.cargo/bin/cargo --verbose
